spring:
  jackson:
    serialization:
      indent-output: true
  jpa:
    driver-class-name: org.postgresql.Driver
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis

jwt:
  secret-key: 3aa15421-55d3-48f2-8372-ddca66362e98
  token-prefix: Bearer
  token-header: Authorization
  expiration-time: 3600000

tenants:
  datasources:
    tenant1:
      url: jdbc:postgresql://localhost:5432/tenant1
      username: postgres
      password: admin
      driverClassName: ${spring.jpa.driver-class-name}
    tenant2:
      url: jdbc:postgresql://localhost:5433/tenant2
      username: postgres
      password: hash
      driverClassName: ${spring.jpa.driver-class-name}

aws:
  s3:
    bucket-name:
    acess-key:
    secret-key:
    region-static:

server:
  servlet:
    context-path: /api

