spring:
  jackson:
    serialization:
      indent-output: true
  datasource:
    url: jdbc:postgresql://localhost:5432/tenancy1
    username: postgres
    password: admin
  jpa:
    driver-class-name: org.postgresql.Driver
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis

server:
  servlet:
    context-path: /api

